new bootscripts

diff --git a/BOOK/bootscripts.old/lfs/sbin/ifup b/BOOK/bootscripts.old/lfs/sbin/ifup
--- a/BOOK/bootscripts.old/lfs/sbin/ifup
+++ b/BOOK/bootscripts.old/lfs/sbin/ifup
@@ -58,66 +58,53 @@ file=/etc/sysconfig/ifconfig.${1}
 log_info_msg "Bringing up the ${1} interface... "
 
 if [ ! -r "${file}" ]; then
-   log_failure_msg2 "${file} is missing or cannot be accessed." 
+   log_warning_msg "\n${file} is missing or cannot be accessed." 
    exit 1
 fi
 
 . $file
 
 if [ "$IFACE" = "" ]; then
-   log_failure_msg2 "${file} does not define an interface [IFACE]."
+   log_failure_msg "\n${file} does not define an interface [IFACE]."
    exit 1
 fi
 
 # Do not process this service if started by boot, and ONBOOT
 # is not set to yes
 if [ "${IN_BOOT}" = "1" -a "${ONBOOT}" != "yes" ]; then
-   log_info_msg2 "skipped"
+   log_info_msg2 "skipped\n"
    exit 0
 fi
 
-for S in ${SERVICE}; do
-  if [ ! -x "/lib/services/${S}" ]; then
-    MSG="\n     Unable to process ${file}.  Either " 
-    MSG="${MSG}the SERVICE '${S} was not present "
-    MSG="${MSG}or cannot be executed."
-    log_failure_msg "$MSG"
-    exit 1
-  fi
-done
+if [ -n "${SERVICE}" -a -x "/lib/services/${SERVICE}" ]; then
+   if [ -z "${CHECK_LINK}"         -o \
+           "${CHECK_LINK}" = "y"   -o \
+           "${CHECK_LINK}" = "yes" -o \
+           "${CHECK_LINK}" = "1" ]; then
 
-if [ -z "${CHECK_LINK}"         -o \
-        "${CHECK_LINK}" = "y"   -o \
-        "${CHECK_LINK}" = "yes" -o \
-        "${CHECK_LINK}" = "1" ]; then
+      #  Bring up the interface
+      if ip link show ${IFACE} > /dev/null 2>&1; then
+         link_status=`ip link show ${IFACE}`
 
-   #  Bring up the interface
-   if ip link show ${IFACE} > /dev/null 2>&1; then
-      link_status=`ip link show ${IFACE}`
-
-      if [ -n "${link_status}" ]; then
-         if ! echo "${link_status}" | grep -q UP; then
-            ip link set ${IFACE} up
+         if [ -n "${link_status}" ]; then
+            if ! echo "${link_status}" | grep -q UP; then
+               ip link set ${IFACE} up
+            fi
          fi
+
+      else
+         log_warning_msg "\nInterface ${IFACE} doesn't exist."
       fi
-
-   else
-      log_failure_msg2 "Interface ${IFACE} doesn't exist."
-      exit 1
    fi
+
+   IFCONFIG=${file} /lib/services/${SERVICE} ${IFACE} up
+
+else
+   MSG="\nUnable to process ${file}.  Either " 
+   MSG="${MSG}the SERVICE variable was not set "
+   MSG="${MSG}or the specified service cannot be executed."
+   log_failure_msg "$MSG"
+   exit 1
 fi
-
-# Set MTU if requested. Check if MTU has a "good" value.
-if test -n "${MTU}"; then
-   if [[ ${MTU} =~ ^[0-9]+$ ]] && [[ $MTU -ge 68 ]] ; then
-      ip link set dev ${IFACE} mtu $MTU
-   else
-      log_info_msg2 "Invalid MTU $MTU"
-   fi
-fi 
-
-for S in ${SERVICE}; do 
-  IFCONFIG=${file} /lib/services/${S} ${IFACE} up
-done
 
 # End /sbin/ifup
